version: '3.8'

services:
  db:
    container_name: postgres
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: iod_payment
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    container_name: app
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=iod_payment
      - POSTGRES_DB_SSL=disable
      - REDIS_DB_HOST=redis
      - REDIS_DB_PORT=6379
      - REDIS_DB_PASSWORD=rasik1234
      - REDIS_DB_DB=0
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    environment:
      REDIS_PASSWORD: rasik1234
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "$REDIS_PASSWORD", "--maxmemory", "512mb", "--maxmemory-policy", "allkeys-lru"]
    networks:
        - default
    volumes:
      - $DOCKERDIR/appdata/redis/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

volumes:
  postgres_data:
